bot: {automerge: true}
conda_forge_output_validation: true
linux_ppc64le:
  enabled: False
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
channel_targets:
  - conda-forge statsmodels_rc
